#!/bin/bash
# Downloads a small, self-contained Python runtime for macOS (arm64 + x86_64) from
# python-build-standalone (https://github.com/astral-sh/python-build-standalone),
# strips out everything not needed to run `python3 -m http.server` (tcl/tk, idle,
# the test suite, headers, docs, pip), and leaves the result in installer/macos/runtime/.
#
# This is a build-time step only — the downloaded/extracted runtime is not committed
# to git (see .gitignore) and is regenerated by this script whenever installers are built.
set -euo pipefail

PY_VERSION="3.12.14"
RELEASE_TAG="20260901"
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
RUNTIME_DIR="$SCRIPT_DIR/runtime"

fetch_arch() {
  local gha_arch="$1"   # aarch64 | x86_64
  local out_dir="$2"    # arm64 | x86_64
  local asset="cpython-${PY_VERSION}%2B${RELEASE_TAG}-${gha_arch}-apple-darwin-install_only.tar.gz"
  local url="https://github.com/astral-sh/python-build-standalone/releases/download/${RELEASE_TAG}/${asset}"
  local tmp_tar="$SCRIPT_DIR/.tmp-${out_dir}.tar.gz"

  echo "Downloading Python ${PY_VERSION} for ${gha_arch}..."
  curl -sL --fail "$url" -o "$tmp_tar"

  rm -rf "$RUNTIME_DIR/$out_dir"
  mkdir -p "$RUNTIME_DIR/$out_dir"
  tar -xzf "$tmp_tar" -C "$RUNTIME_DIR/$out_dir" --strip-components=1
  rm -f "$tmp_tar"

  echo "Trimming unused parts (tcl/tk, idle, test suite, docs, pip, headers)..."
  local pylibdir="$RUNTIME_DIR/$out_dir/lib/python3.12"
  rm -rf \
    "$RUNTIME_DIR/$out_dir/lib/tcl9.0" \
    "$RUNTIME_DIR/$out_dir/lib/tk9.0" \
    "$RUNTIME_DIR/$out_dir/lib/itcl4.3.8" \
    "$RUNTIME_DIR/$out_dir/lib/thread3.0.6" \
    "$RUNTIME_DIR/$out_dir/lib/tcl9" \
    "$RUNTIME_DIR/$out_dir/include" \
    "$RUNTIME_DIR/$out_dir/share/man" \
    "$RUNTIME_DIR/$out_dir/share/doc" \
    "$pylibdir/test" \
    "$pylibdir/tkinter" \
    "$pylibdir/idlelib" \
    "$pylibdir/lib2to3" \
    "$pylibdir/turtledemo" \
    "$RUNTIME_DIR/$out_dir/bin/pip" \
    "$RUNTIME_DIR/$out_dir/bin/pip3" \
    "$RUNTIME_DIR/$out_dir/bin/pip3.12" \
    "$RUNTIME_DIR/$out_dir/bin/idle3" \
    "$RUNTIME_DIR/$out_dir/bin/idle3.12" \
    "$RUNTIME_DIR/$out_dir/bin/2to3" \
    "$RUNTIME_DIR/$out_dir/bin/2to3-3.12" \
    2>/dev/null || true

  if [ ! -x "$RUNTIME_DIR/$out_dir/bin/python3" ]; then
    echo "ERROR: expected binary missing at $RUNTIME_DIR/$out_dir/bin/python3" >&2
    exit 1
  fi

  # Only actually execute the binary if it matches this machine's architecture
  # (e.g. building the x86_64 runtime on an arm64 Mac can't run it here without Rosetta).
  if [ "$(uname -m)" = "$gha_arch" ] || { [ "$(uname -m)" = "arm64" ] && [ "$gha_arch" = "aarch64" ]; }; then
    echo "Verifying the trimmed runtime actually runs (native arch)..."
    "$RUNTIME_DIR/$out_dir/bin/python3" -c "import http.server, socketserver; print('OK:', __import__('sys').version)"
  else
    echo "Skipping execution check for $gha_arch (not this machine's architecture) — file presence only."
  fi

  du -sh "$RUNTIME_DIR/$out_dir"
}

mkdir -p "$RUNTIME_DIR"
fetch_arch "aarch64" "arm64"
fetch_arch "x86_64" "x86_64"

echo "Done. Runtimes are in $RUNTIME_DIR/{arm64,x86_64}"
